[package]
name = "bb8-surrealdb"
version = "0.1.0"
edition = "2021"

[features]
tikv = ["surrealdb/kv-tikv"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bb8 = "0.8"
async-trait = "0.1"
surrealdb = "1.0.0-beta.8"